version: '3'
services:
# Back
  # mongo server
  mongo:
    container_name: pytheas_mongoserver
    image: "mongo:3.4"
    restart: always
    command: mongod
    ports:
     - "27017:27017"
    volumes: 
     - './data/mongo:/data/db'
    network_mode: bridge
    hostname: mongod
  
  # restapp
  restapp:
    container_name: pytheas_restapp
    build: ./rest/
    network_mode: bridge
    hostname: restapp
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    ports:
     - "5003:5003"
    volumes:
     - './rest:/opt/pytheas_rest'
     - './rest/conf:/opt/pytheas_rest/conf'

  # # worker:
  #   container_name: restapp
  #   build: ./worker/
  #   network_mode: bridge
  # ports:
  #    - "5003:5003"
  #   hostname: worker
  #   volumes:
  #    - './rest:/opt/pytheas_worker'
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo

# Front
  # mongo client
  mongoclient:
    container_name: pytheas_mongoclient
    image: "mongoclient/mongoclient"
    restart: always
    ports:
     - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  # wepapp
  webapp:
    container_name: pytheas_webapp
    build: ./
    network_mode: bridge
    hostname: webapp
    restart: always
    ports:
     - "5000:5000"
    depends_on:
     - restapp
    links:
      - restapp
      - mongo
    volumes:
     - '.:/opt/pytheas'
     - './data:/opt/pytheas/data'
     - './conf:/opt/pytheas/conf'
