version: '2'
services:
  web:
    container_name: cortext_pytheas_web
    build: .
    ports:
     - "5000:8080"
    depends_on:
     - mongo
    volumes:
     - '.:/opt/pytheas'
     - './data:/opt/pytheas/data'
     - './conf:/opt/pytheas/conf'
  mongo:
    container_name: cortext_pytheas_mongoserver
    image: "mongo:3.4"
    ports: 
     - "27018:27018"
    volumes: 
     - './data/mongo:/data/db'
  mongoclient:
    container_name: cortext_pytheas_mongoclient
    image: "mongoclient/mongoclient"
    ports:
     - "3000:3000"
    depends_on:
      - mongo
  rest:
    container_name: cortext_pytheas_rest
    build: ./rest/
    ports:
     - "5002:5002"
    volumes:
     - './rest:/opt/pytheas_rest'
    depends_on:
      - mongo
      - web