version: '3'
services:

  # Back
  mongo:
    container_name: MONGOSERVER
    image: "mongo:3.4"
    command: mongod
    expose:
     - "27017"
    volumes: 
     - './data/mongo:/data/db'
    network_mode: bridge
    hostname: mongod
  
  # Back
  restapp:
    container_name: restapp
    build: ./rest/
    expose:
     - "5002"
     - "27017"
    network_mode: bridge
    hostname: restapp
    volumes:
     - './rest:/opt/pytheas_rest'
    depends_on:
      - mongo
    links:
      - mongo

  # Back
  # worker:
  #   container_name: restapp
  #   build: ./worker/
  #   expose:
  #    - "5003"
  #    - "27017"
  #   network_mode: bridge
  #   hostname: worker
  #   volumes:
  #    - './rest:/opt/pytheas_worker'
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo

  # Front
  mongoclient:
    container_name: mongoclient
    image: "mongoclient/mongoclient"
    ports:
     - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  # Front
  webapp:
    container_name: webapp
    hostname: webapp
    network_mode: bridge

    build: ./
    ports:
     - "8080:8080"
    expose:
     - "8080"
    depends_on:
     - restapp
    links:
      - restapp
      - mongo
    volumes:
     - '.:/opt/pytheas'
     - './data:/opt/pytheas/data'
     - './conf:/opt/pytheas/conf'